concatenate the one range with another range
phovea/phovea_core pull request #84
Opened 2017-02-20 16:08 UTC by bikramkawan

2017-02-20 16:11 UTC, mstreit commented
@bikramkawan, you can assign them as reviewers, see button on the right.

2017-02-20 16:12 UTC, thinkh commented
@mstreit He can't, because he isn't a collaborator to this repository.

2017-02-20 16:15 UTC, thinkh submitted a review, later dismissed

2017-02-20 16:15 UTC, sgratzl requested changes
several copy paste errors that needs to be fixed + I don't know whether `concat` is the right name for the logic that it implements

2017-02-20 16:15 UTC, sgratzl commented on src/range/CompositeRange1D.ts
> +    const r = this.groups.length > 1 ? super.union(other, size) : undefined;
why is `super.union` called instead of `.concat`?

2017-02-20 16:15 UTC, sgratzl commented on src/range/CompositeRange1D.ts
> +    return new CompositeRange1D(this.name, this.groups.map((g) => <Range1DGroup>g.union(other, size)), r);
again, `union` instead of `concat`

2017-02-20 16:15 UTC, sgratzl commented on src/range/Range1D.ts
> +  concat(other: Range1D, size?: number): Range1D {
for me `concat` doesn't imply for me that there are no duplicates allowed. At least when I concatenate two strings, duplicates are allowed.

2017-02-20 16:15 UTC, sgratzl commented on src/range/Range1DGroup.ts
> +    const r = super.union(other, size);
why is `super.union` called?

2017-02-20 16:17 UTC, thinkh commented on src/range/Range1D.ts
> +  concat(other: Range1D, size?: number): Range1D {
Would `join` be a better name?

2017-02-20 16:18 UTC, sgratzl commented on src/range/Range1D.ts
> +  concat(other: Range1D, size?: number): Range1D {
there is already a join method: https://github.com/phovea/phovea_core/blob/develop/src/range/index.ts#L50

2017-02-20 16:19 UTC, sgratzl commented
I don't get the motivation behind this method?

2017-02-20 16:21 UTC, thinkh commented on src/range/Range1D.ts
> +  concat(other: Range1D, size?: number): Range1D {
We tried the `join` function that you send. However, it joins multiple dimensions to a single. We need to join multiple Range1D to a single one.

2017-02-20 16:22 UTC, thinkh commented
@sgratzl `Range1D.union()` is sorting the results, the proposed `Range1D.concat()` isn't. It's important for mothertable to *not* sort the results.

2017-02-20 16:23 UTC, sgratzl commented
I get the functionality but not the usecase

2017-02-20 16:32 UTC, bikramkawan commented
The use case is similar to this.
https://github.com/Caleydo/mothertable/issues/103
For example: 
The data is sorted by country > career status > gender. 
Consider we have already sorted country and career status which gives use array of Range.
What I was looking for is similar as below:
![image](https://cloud.githubusercontent.com/assets/12292333/23133592/f1e74a1a-f791-11e6-8d23-3678a371d509.png)
The index of each sorted is [0],[9] and so on. This means these are the array of Range Object. In the end we need to join to form single Range object which is exactly shown in last array [0,9.. 4,7]. 
The final  range is used to render the visualization.

2017-02-20 16:40 UTC, sgratzl commented
why is the criteria "no-duplicates" that the union/concat method fulfills needed?

2017-02-20 16:48 UTC, bikramkawan commented
what do you mean by no-duplicates here?

2017-02-20 16:50 UTC, sgratzl commented
> @sgratzl Range1D.union() is sorting the results, the proposed Range1D.concat() isn't. 

union is a set operation, i.e. it ensures that there are no duplicates in the set and since it is a set, the order doesn't matter. 

the current version of `concat` uses 90% of the union logic also ensuring that there are no duplicates.

2017-02-20 16:52 UTC, bikramkawan commented
Yes. it uses the logic of union but we need the union without the sorting. The current union method returns the indexes after sorting.

2017-02-20 19:09 UTC, sgratzl commented on src/range/Range.ts
> +    if (this.isAll || other.isNone) {
does it make sense, if this or the other contain all ids, not to concatenate them?

2017-02-20 19:09 UTC, sgratzl commented on src/range/Range1D.ts
> +    const r = this.iter(size).asList();
why need both list converted to their indices before combining them?

2017-02-20 19:09 UTC, sgratzl commented on src/range/CompositeRange1D.ts
> +    return new CompositeRange1D(this.name, this.groups.map((g) => <Range1DGroup>g.concat(other, size)), r);
does it make sense to add the items to each group within a composite?

2017-03-09 10:01 UTC, thinkh commented
@bikramkawan What is the status here? Do you still need that functionality for mothertable?

2017-03-09 10:04 UTC, bikramkawan commented
@thinkh  Currently, I am using push list method. we can keep this for future reference if there is no any harm in our branch.

2017-03-09 10:07 UTC, closed without merging